### ISSUE TITLE
Join link is broken

### ISSUE THREAD

**Issue by mark-wiemer** [ahkscript/ahkscript.github.io#16]
The link at https://ahkscript.github.io is broken :(

> Want to be a member of the ahkscript.org GitHub group? Join with a simple post of your GitHub username here: 
> http://ahkscript.org/boards/viewtopic.php?t=936

**Comment by joedf** [comment]
Yeah, I think we need to  fix redirect ahkscript.org in general.

For now, the link is https://www.autohotkey.com/boards/viewtopic.php?t=936

Thanks for reporting this.
