### ISSUE TITLE
Improved responsive design

### ISSUE THREAD

**Issue by dufferzafar** [ahkscript/ahkscript.github.io#7]
When viewing the website on a mobile device, it looks a bit odd - as, the header image (AHK) makes the text push to the right. Also, there's no navigation bar.

I could work on these things, but the only experience I have is with [Bootstrap](http://getbootstrap.com/), so If you don't have a problem adding it as a dependency, please let me know, and I can work on making it work on mobile devices better :)

**Comment by lipkau** [comment]
Suggestion: close ticket, as page has been redesigned. If further responsive optimizations are needed, as new ticket/PR can be opened.
